{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16e520fc-e561-460b-a08d-1847a5742823",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "Starting Operations API\n",
      "============================================================\n",
      "Database initialized at: c:\\Users\\ibrahem\\Desktop\\EnerAI\\database\\energyW.db\n",
      "Loaded 5589 records from database\n",
      "Total records available: 5589\n",
      "Date range: 2020-01-31 00:00:00 to 2025-09-30 00:00:00\n",
      "Departments: 18\n",
      "Admin Areas: 3\n",
      "============================================================\n",
      "API Server Ready\n",
      "Listening on: http://0.0.0.0:8001\n",
      "Test endpoints:\n",
      "  - GET /api/health\n",
      "  - GET /api/debug\n",
      "  - GET /api/test\n",
      "  - GET /api/metrics\n",
      "  - POST /api/rewrite\n",
      "  - POST /api/save-report (NEW)\n",
      "============================================================\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on all addresses (0.0.0.0)\n",
      " * Running on http://127.0.0.1:8001\n",
      " * Running on http://166.87.240.138:8001\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [15/Dec/2025 14:50:13] \"OPTIONS /api/report HTTP/1.1\" 204 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating report for quarter=None, department=None, adminArea=None, stream=None\n",
      "Loaded 5589 records from database\n",
      "Calling Ollama AI...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:50:44] \"POST /api/report HTTP/1.1\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Raw Ollama Response (truncated):\n",
      "{\n",
      "  \"executive_summary\": \"The company's performance across various operational metrics for Full Year 2024 is presented below. Key observations include a 2.11% achievement rate above target for production, 1.82% utilization rate above target for throughput, and significant energy usage of 236,096,079 units.\",\n",
      "  \n",
      "  \"key_insights\": \"- Production achieved 102.11% of the target with an average actual value of 254,439.15.\n",
      "- Throughput utilized 101.82% of the target capacity with an average actual valu\n",
      "JSON Parse Error: Invalid \\escape: line 4 column 334 (char 646)\n",
      "Raw response: {\n",
      "  \"executive_summary\": \"The company's performance across various operational metrics for Full Year 2024 is presented below. Key observations include a 2.11% achievement rate above target for production, 1.82% utilization rate above target for throughput, and significant energy usage of 236,096,079 units.\",\n",
      "  \n",
      "  \"key_insights\": \"- Production achieved 102.11% of the target with an average actual value of 254,439.15.\n",
      "- Throughput utilized 101.82% of the target capacity with an average actual value of 789,674.01.\n",
      "- Refining showed a notable underperformance with a mere 97.32% achievement rate and an average actual value of 430,712.34.\n",
      "\n",
      "\\ \n",
      "- The top 5 production streams for the period were UP-J71 with a variance of 21.96%, followed closely by UP-E22 at 21.96%.\n",
      "- Conversely, the bottom 5 underperforming streams included UP-V40 with a negative variance of -17.99% and UP-M73 at -17.99%.\n",
      "\n",
      "\\ \n",
      "- Energy usage was substantial, totaling 236,096,079 units.\n",
      "- Average actual downtime was 39.75 minutes.\n",
      "- The top departments contributing to high downtime events were DS Utilities (33) and MS Storage & Term (31).\"\n",
      "\n",
      "  \n",
      "  \"anomalies\": \"High energy usage across all operational areas necessitates a thorough review of equipment efficiency, maintenance schedules, and replacement policies.\n",
      "Average actual downtime indicates room for improvement in asset management and predictive maintenance practices. Identifying the root causes behind high downtime events is crucial to prevent future occurrences.\"\n",
      "\n",
      "  \n",
      "  \"recommendations\": \"1. Conduct an extensive energy audit to pinpoint areas where operational efficiency can be improved without compromising production rates.\n",
      "2. Develop a comprehensive predictive maintenance program tailored to each department's unique equipment needs and operational patterns.\n",
      "3. Streamline asset management processes by leveraging real-time data analytics, artificial intelligence, and IoT sensors for enhanced decision-making.\"\n",
      "}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:50:50] \"GET /api/reports HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Dec/2025 14:51:01] \"OPTIONS /api/report HTTP/1.1\" 204 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating report for quarter=None, department=None, adminArea=None, stream=None\n",
      "Loaded 5589 records from database\n",
      "Calling Ollama AI...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:51:19] \"POST /api/report HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Raw Ollama Response (truncated):\n",
      "{\n",
      "  \"executive_summary\": \"Based on our comprehensive analysis of operational performance across all three sectors (upstream, midstream, and downstream) for the full year 2024, we observed a mixed bag of achievements and underperformance. The total actual production volume was 102.11% of target, while throughput utilization reached 101.82%. However, there were notable variances in performance across different admin areas, departments, and streams.\\n- Notable underperforming operational areas incl\n",
      "Report saved with ID: 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:55:16] \"OPTIONS /api/rewrite HTTP/1.1\" 204 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== Text Rewrite Request ===\n",
      "Original length: 678 chars\n",
      "Instructions: All available data from 2021 to 2025 were used in this report, rather than limiting the analysis to ...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:55:23] \"POST /api/rewrite HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Rewritten length: 692 chars\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:56:23] \"OPTIONS /api/save-report HTTP/1.1\" 204 -\n",
      "127.0.0.1 - - [15/Dec/2025 14:56:23] \"POST /api/save-report HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Report saved to database with ID: 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:56:25] \"GET /api/reports HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Dec/2025 14:56:29] \"OPTIONS /api/reports/1 HTTP/1.1\" 204 -\n",
      "127.0.0.1 - - [15/Dec/2025 14:56:29] \"DELETE /api/reports/1 HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Dec/2025 14:56:29] \"GET /api/reports HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Dec/2025 14:57:54] \"OPTIONS /api/report HTTP/1.1\" 204 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating report for quarter=None, department=None, adminArea=None, stream=None\n",
      "Loaded 5589 records from database\n",
      "Calling Ollama AI...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 14:58:09] \"POST /api/report HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Raw Ollama Response (truncated):\n",
      "{\n",
      "  \"executive_summary\": \"Overall, the company achieved a strong performance across various metrics for the full year 2024. Key highlights include a 102.11% achievement rate in production, 101.82% utilization rate in throughput, and 21.96% variance in top-performing streams. However, some underperforming areas and streams require attention to optimize efficiency and minimize downtime.\",\n",
      "  \"key_insights\": \"- Production achieved 102.11% of target with an average actual of 254439.15 barrels per day\n",
      "Report saved with ID: 3\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Dec/2025 15:01:28] \"GET /api/reports HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, jsonify, request\n",
    "from flask_cors import CORS\n",
    "import pandas as pd\n",
    "import sqlite3\n",
    "import ollama\n",
    "import json\n",
    "from datetime import datetime\n",
    "import traceback\n",
    "import math\n",
    "import os\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "\n",
    "CORS(app, resources={r\"/api/*\": {\n",
    "    \"origins\": \"*\",\n",
    "    \"methods\": [\"GET\", \"POST\", \"PUT\", \"DELETE\", \"OPTIONS\"],\n",
    "    \"allow_headers\": [\"Content-Type\"],\n",
    "    \"supports_credentials\": False\n",
    "}})\n",
    "\n",
    "\n",
    "@app.before_request\n",
    "def handle_preflight():\n",
    "    if request.method == 'OPTIONS':\n",
    "        return '', 204\n",
    "\n",
    "DB_PATH = \"energyW.db\"\n",
    "\n",
    "\n",
    "# ================================\n",
    "# DATABASE INITIALIZATION\n",
    "# ================================\n",
    "def init_db():\n",
    "    \"\"\"Initialize database with reports table and migrate if needed\"\"\"\n",
    "    conn = sqlite3.connect(DB_PATH)\n",
    "    cur = conn.cursor()\n",
    "\n",
    "    # Create reports table if not exists\n",
    "    cur.execute(\"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS reports (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            created_at TEXT NOT NULL,\n",
    "            updated_at TEXT NOT NULL,\n",
    "            quarter TEXT,\n",
    "            report_json TEXT NOT NULL,\n",
    "            raw_text TEXT,\n",
    "            metadata TEXT,\n",
    "            text_content TEXT,\n",
    "            stats_json TEXT,\n",
    "            context_json TEXT\n",
    "        )\n",
    "    \"\"\")\n",
    "    \n",
    "    # Migration: Add missing columns if they don't exist\n",
    "    # Get existing columns\n",
    "    cur.execute(\"PRAGMA table_info(reports)\")\n",
    "    existing_columns = [row[1] for row in cur.fetchall()]\n",
    "    \n",
    "    # Add text_content if missing\n",
    "    if 'text_content' not in existing_columns:\n",
    "        cur.execute(\"ALTER TABLE reports ADD COLUMN text_content TEXT\")\n",
    "        print(\"Added column: text_content\")\n",
    "    \n",
    "    # Add stats_json if missing\n",
    "    if 'stats_json' not in existing_columns:\n",
    "        cur.execute(\"ALTER TABLE reports ADD COLUMN stats_json TEXT\")\n",
    "        print(\"Added column: stats_json\")\n",
    "    \n",
    "    # Add context_json if missing\n",
    "    if 'context_json' not in existing_columns:\n",
    "        cur.execute(\"ALTER TABLE reports ADD COLUMN context_json TEXT\")\n",
    "        print(\"Added column: context_json\")\n",
    "\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "    print(f\"Database initialized at: {os.path.abspath(DB_PATH)}\")\n",
    "\n",
    "\n",
    "# ================================\n",
    "# DATA LOADING\n",
    "# ================================\n",
    "def load_data():\n",
    "    \"\"\"Load metrics data from database\"\"\"\n",
    "    try:\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        df = pd.read_sql_query(\"SELECT * FROM upstream_metrics\", conn)\n",
    "        conn.close()\n",
    "\n",
    "        if df.empty:\n",
    "            print(\"WARNING: DataFrame is empty!\")\n",
    "            return pd.DataFrame()\n",
    "\n",
    "        # Ensure Date is datetime (handle mixed formats)\n",
    "        df[\"Date\"] = pd.to_datetime(df[\"Date\"], format='mixed', errors='coerce')\n",
    "        df[\"Quarter\"] = df[\"Date\"].dt.quarter\n",
    "\n",
    "        print(f\"Loaded {len(df)} records from database\")\n",
    "        return df\n",
    "    except Exception as e:\n",
    "        print(f\"Error loading data: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return pd.DataFrame()\n",
    "\n",
    "# ================================\n",
    "# FILTERING\n",
    "# ================================\n",
    "def filter_by_quarter(df, quarter):\n",
    "    \"\"\"Filter dataframe by quarter\"\"\"\n",
    "    if not quarter or quarter == \"\":\n",
    "        return df\n",
    "\n",
    "    try:\n",
    "        q = int(quarter)\n",
    "        if q in (1, 2, 3, 4):\n",
    "            filtered = df[df[\"Quarter\"] == q]\n",
    "            return filtered\n",
    "    except Exception:\n",
    "        pass\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "def filter_data(df, filters):\n",
    "    \"\"\"Apply multiple filters to dataframe\"\"\"\n",
    "    if not filters:\n",
    "        return df\n",
    "\n",
    "    if filters.get(\"department\"):\n",
    "        df = df[df[\"Department\"] == filters[\"department\"]]\n",
    "\n",
    "    if filters.get(\"stream\"):\n",
    "        df = df[df[\"Stream\"] == filters[\"stream\"]]\n",
    "\n",
    "    if filters.get(\"adminArea\"):\n",
    "        df = df[df[\"AdminArea\"] == filters[\"adminArea\"]]\n",
    "\n",
    "    if filters.get(\"quarter\"):\n",
    "        df = filter_by_quarter(df, filters[\"quarter\"])\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ================================\n",
    "# SUMMARY BUILDER FOR AI\n",
    "# ================================\n",
    "def build_summary(df):\n",
    "    \"\"\"Build comprehensive summary for AI analysis based on current schema\"\"\"\n",
    "    if df.empty:\n",
    "        return {\n",
    "            \"error\": \"No data available\",\n",
    "            \"records_count\": 0\n",
    "        }\n",
    "\n",
    "    summary = {\n",
    "        \"records_count\": len(df),\n",
    "        \"date_range\": {\n",
    "            \"start\": df[\"Date\"].min().strftime(\"%Y-%m-%d\"),\n",
    "            \"end\": df[\"Date\"].max().strftime(\"%Y-%m-%d\")\n",
    "        }\n",
    "    }\n",
    "\n",
    "    # Production metrics (Upstream)\n",
    "    if \"Production_Actual\" in df.columns and \"Production_Target\" in df.columns:\n",
    "        total_target = float(df[\"Production_Target\"].fillna(0).sum())\n",
    "        total_actual = float(df[\"Production_Actual\"].fillna(0).sum())\n",
    "\n",
    "        summary[\"production\"] = {\n",
    "            \"total_actual\": total_actual,\n",
    "            \"total_target\": total_target,\n",
    "            \"avg_actual\": float(df[\"Production_Actual\"].mean()),\n",
    "            \"avg_target\": float(df[\"Production_Target\"].mean()),\n",
    "            \"achievement_rate\": float((total_actual / total_target * 100) if total_target > 0 else 0)\n",
    "        }\n",
    "\n",
    "    # Throughput metrics (Midstream)\n",
    "    if \"Throughput_Actual\" in df.columns and \"Throughput_Target\" in df.columns:\n",
    "        total_target = float(df[\"Throughput_Target\"].fillna(0).sum())\n",
    "        total_actual = float(df[\"Throughput_Actual\"].fillna(0).sum())\n",
    "\n",
    "        summary[\"throughput\"] = {\n",
    "            \"total_actual\": total_actual,\n",
    "            \"total_target\": total_target,\n",
    "            \"avg_actual\": float(df[\"Throughput_Actual\"].mean()),\n",
    "            \"avg_target\": float(df[\"Throughput_Target\"].mean()),\n",
    "            \"utilization_rate\": float((total_actual / total_target * 100) if total_target > 0 else 0)\n",
    "        }\n",
    "\n",
    "    # Compression metrics (Midstream)\n",
    "    if \"Compression_Actual\" in df.columns and \"Compression_Target\" in df.columns:\n",
    "        summary[\"compression\"] = {\n",
    "            \"avg_actual\": float(df[\"Compression_Actual\"].mean()),\n",
    "            \"avg_target\": float(df[\"Compression_Target\"].mean())\n",
    "        }\n",
    "\n",
    "    # Processing metrics (Midstream)\n",
    "    if \"Processing_Actual\" in df.columns and \"Processing_Target\" in df.columns:\n",
    "        total_target = float(df[\"Processing_Target\"].fillna(0).sum())\n",
    "        total_actual = float(df[\"Processing_Actual\"].fillna(0).sum())\n",
    "\n",
    "        summary[\"processing\"] = {\n",
    "            \"total_actual\": total_actual,\n",
    "            \"total_target\": total_target,\n",
    "            \"avg_actual\": float(df[\"Processing_Actual\"].mean()),\n",
    "            \"avg_target\": float(df[\"Processing_Target\"].mean())\n",
    "        }\n",
    "\n",
    "    # Refining metrics (Downstream)\n",
    "    if \"Refinery_Actual\" in df.columns and \"Refinery_Target\" in df.columns:\n",
    "        total_target = float(df[\"Refinery_Target\"].fillna(0).sum())\n",
    "        total_actual = float(df[\"Refinery_Actual\"].fillna(0).sum())\n",
    "\n",
    "        summary[\"refining\"] = {\n",
    "            \"total_actual\": total_actual,\n",
    "            \"total_target\": total_target,\n",
    "            \"avg_actual\": float(df[\"Refinery_Actual\"].mean()),\n",
    "            \"avg_target\": float(df[\"Refinery_Target\"].mean())\n",
    "        }\n",
    "\n",
    "    # Yield metrics (Downstream)\n",
    "    if \"Yield_Actual\" in df.columns and \"Yield_Target\" in df.columns:\n",
    "        summary[\"yield\"] = {\n",
    "            \"avg_actual\": float(df[\"Yield_Actual\"].mean()),\n",
    "            \"avg_target\": float(df[\"Yield_Target\"].mean())\n",
    "        }\n",
    "\n",
    "    # Energy metrics (shared)\n",
    "    if \"Energy_Actual\" in df.columns:\n",
    "        summary[\"energy\"] = {\n",
    "            \"total_actual\": float(df[\"Energy_Actual\"].sum()),\n",
    "            \"avg_actual\": float(df[\"Energy_Actual\"].mean())\n",
    "        }\n",
    "\n",
    "    # Downtime metrics\n",
    "    if \"Downtime_Min\" in df.columns:\n",
    "        summary[\"downtime\"] = {\n",
    "            \"total_downtime_min\": int(df[\"Downtime_Min\"].sum()),\n",
    "            \"avg_downtime_min\": float(df[\"Downtime_Min\"].mean()),\n",
    "            \"high_downtime_events\": int(df[df[\"Downtime_Min\"] >= 60].shape[0])\n",
    "        }\n",
    "\n",
    "    # Organizational breakdown\n",
    "    if \"AdminArea\" in df.columns:\n",
    "        summary[\"admin_areas\"] = {\n",
    "            \"count\": int(df[\"AdminArea\"].nunique()),\n",
    "            \"list\": df[\"AdminArea\"].unique().tolist()\n",
    "        }\n",
    "\n",
    "    if \"Department\" in df.columns:\n",
    "        summary[\"departments\"] = {\n",
    "            \"count\": int(df[\"Department\"].nunique()),\n",
    "            \"list\": df[\"Department\"].unique().tolist()\n",
    "        }\n",
    "\n",
    "    if \"Stream\" in df.columns:\n",
    "        summary[\"streams\"] = {\n",
    "            \"count\": int(df[\"Stream\"].nunique()),\n",
    "            \"list\": df[\"Stream\"].unique().tolist()[:10]  # top 10 for context\n",
    "        }\n",
    "\n",
    "    # Performance based on production variance if available\n",
    "    if \"Production_Actual\" in df.columns and \"Production_Target\" in df.columns:\n",
    "        tmp = df.copy()\n",
    "        tmp = tmp[tmp[\"Production_Target\"] > 0].copy()\n",
    "\n",
    "        if not tmp.empty:\n",
    "            tmp[\"Prod_Variance_pct\"] = (tmp[\"Production_Actual\"] - tmp[\"Production_Target\"]) / tmp[\"Production_Target\"] * 100.0\n",
    "\n",
    "            top_performers = tmp.nlargest(5, \"Prod_Variance_pct\")[[\"Stream\", \"Prod_Variance_pct\"]].to_dict(\"records\")\n",
    "            underperformers = tmp.nsmallest(5, \"Prod_Variance_pct\")[[\"Stream\", \"Prod_Variance_pct\"]].to_dict(\"records\")\n",
    "\n",
    "            summary[\"production_performance\"] = {\n",
    "                \"top_5\": [\n",
    "                    {\n",
    "                        \"stream\": r[\"Stream\"],\n",
    "                        \"variance_pct\": float(r[\"Prod_Variance_pct\"])\n",
    "                    }\n",
    "                    for r in top_performers\n",
    "                ],\n",
    "                \"bottom_5\": [\n",
    "                    {\n",
    "                        \"stream\": r[\"Stream\"],\n",
    "                        \"variance_pct\": float(r[\"Prod_Variance_pct\"])\n",
    "                    }\n",
    "                    for r in underperformers\n",
    "                ]\n",
    "            }\n",
    "\n",
    "    return summary\n",
    "\n",
    "\n",
    "# ================================\n",
    "# HELPER FUNCTIONS\n",
    "# ================================\n",
    "def clean_json_record(record):\n",
    "    \"\"\"Clean NaN and inf values from record for JSON serialization\"\"\"\n",
    "    clean = {}\n",
    "    for k, v in record.items():\n",
    "        if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):\n",
    "            clean[k] = None\n",
    "        elif pd.isna(v):  # Handle NaN for other types\n",
    "            clean[k] = None\n",
    "        else:\n",
    "            clean[k] = v\n",
    "    return clean\n",
    "\n",
    "\n",
    "# ================================\n",
    "# API ENDPOINTS\n",
    "# ================================\n",
    "\n",
    "@app.route(\"/api/health\", methods=[\"GET\"])\n",
    "def health_check():\n",
    "    \"\"\"Health check endpoint\"\"\"\n",
    "    return jsonify({\n",
    "        \"status\": \"ok\",\n",
    "        \"service\": \"Aramco Operations API\",\n",
    "        \"timestamp\": datetime.now().isoformat(),\n",
    "        \"database\": os.path.exists(DB_PATH)\n",
    "    })\n",
    "\n",
    "\n",
    "@app.route(\"/api/metrics\", methods=[\"GET\"])\n",
    "def get_metrics():\n",
    "    \"\"\"Get all metrics with optional filters\"\"\"\n",
    "    try:\n",
    "        quarter = request.args.get(\"quarter\")\n",
    "        department = request.args.get(\"department\")\n",
    "        admin_area = request.args.get(\"adminArea\")\n",
    "        stream = request.args.get(\"stream\")\n",
    "\n",
    "        print(f\"\\n=== GET /api/metrics ===\")\n",
    "        print(f\"Parameters: quarter={quarter}, department={department}, adminArea={admin_area}, stream={stream}\")\n",
    "\n",
    "        df = load_data()\n",
    "\n",
    "        if df.empty:\n",
    "            print(\"ERROR: DataFrame is empty after loading\")\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"No data available in database\",\n",
    "                \"records\": []\n",
    "            }), 404\n",
    "\n",
    "        # Apply filters\n",
    "        filters = {}\n",
    "        if quarter:\n",
    "            filters[\"quarter\"] = quarter\n",
    "        if department:\n",
    "            filters[\"department\"] = department\n",
    "        if admin_area:\n",
    "            filters[\"adminArea\"] = admin_area\n",
    "        if stream:\n",
    "            filters[\"stream\"] = stream\n",
    "\n",
    "        if filters:\n",
    "            df = filter_data(df, filters)\n",
    "\n",
    "        # Check if data exists after filtering\n",
    "        if df.empty:\n",
    "            print(\"WARNING: No data after filtering\")\n",
    "            return jsonify({\n",
    "                \"status\": \"ok\",  # Changed from \"error\" to \"ok\"\n",
    "                \"message\": \"No data matches the selected filters\",\n",
    "                \"records\": [],\n",
    "                \"count\": 0,\n",
    "                \"filters\": filters\n",
    "            })\n",
    "\n",
    "        # Convert date to string\n",
    "        df[\"Date\"] = df[\"Date\"].dt.strftime(\"%Y-%m-%d\")\n",
    "\n",
    "        # Convert NaN → None (JSON-safe)\n",
    "        records = df.to_dict(orient=\"records\")\n",
    "        records = [clean_json_record(r) for r in records]\n",
    "\n",
    "        print(f\"Returning {len(records)} records\")\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"records\": records,\n",
    "            \"count\": len(records),\n",
    "            \"filters\": filters\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error in /api/metrics: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e),\n",
    "            \"records\": []\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/summary\", methods=[\"GET\"])\n",
    "def get_summary():\n",
    "    \"\"\"Get summary statistics\"\"\"\n",
    "    try:\n",
    "        quarter = request.args.get(\"quarter\")\n",
    "        department = request.args.get(\"department\")\n",
    "        admin_area = request.args.get(\"adminArea\")\n",
    "        stream = request.args.get(\"stream\")\n",
    "\n",
    "        df = load_data()\n",
    "\n",
    "        if df.empty:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"No data available\"\n",
    "            }), 404\n",
    "\n",
    "        # Apply filters\n",
    "        filters = {}\n",
    "        if quarter:\n",
    "            filters[\"quarter\"] = quarter\n",
    "        if department:\n",
    "            filters[\"department\"] = department\n",
    "        if admin_area:\n",
    "            filters[\"adminArea\"] = admin_area\n",
    "        if stream:\n",
    "            filters[\"stream\"] = stream\n",
    "\n",
    "        if filters:\n",
    "            df = filter_data(df, filters)\n",
    "\n",
    "        # Build period label\n",
    "        period_label = \"Full Year 2024\"\n",
    "        if quarter:\n",
    "            period_label = f\"Q{quarter} 2024\"\n",
    "\n",
    "        if department:\n",
    "            period_label += f\" - {department}\"\n",
    "        if admin_area:\n",
    "            period_label += f\" - {admin_area}\"\n",
    "        if stream:\n",
    "            period_label += f\" - Stream {stream}\"\n",
    "\n",
    "        summary = build_summary(df)\n",
    "        summary[\"period_label\"] = period_label\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"summary\": summary\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error in /api/summary: {e}\")\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/report\", methods=[\"POST\"])\n",
    "def generate_report():\n",
    "    \"\"\"Generate AI-powered report using Ollama\"\"\"\n",
    "    try:\n",
    "        payload = request.get_json() or {}\n",
    "        quarter = payload.get(\"quarter\")\n",
    "        department = payload.get(\"department\")\n",
    "        admin_area = payload.get(\"adminArea\")\n",
    "        stream = payload.get(\"stream\")\n",
    "\n",
    "        print(f\"Generating report for quarter={quarter}, department={department}, adminArea={admin_area}, stream={stream}\")\n",
    "\n",
    "        df = load_data()\n",
    "\n",
    "        if df.empty:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"No data available for report generation\"\n",
    "            }), 404\n",
    "\n",
    "        # Apply filters\n",
    "        filters = {}\n",
    "        if quarter:\n",
    "            filters[\"quarter\"] = quarter\n",
    "        if department:\n",
    "            filters[\"department\"] = department\n",
    "        if admin_area:\n",
    "            filters[\"adminArea\"] = admin_area\n",
    "        if stream:\n",
    "            filters[\"stream\"] = stream\n",
    "\n",
    "        df_filtered = filter_data(df, filters) if filters else df\n",
    "\n",
    "        if df_filtered.empty:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"No data matches the selected filters\"\n",
    "            }), 404\n",
    "\n",
    "        # Build summary\n",
    "        summary = build_summary(df_filtered)\n",
    "\n",
    "        # Determine period label\n",
    "        if quarter:\n",
    "            period_label = f\"Q{quarter} 2024\"\n",
    "        else:\n",
    "            period_label = \"Full Year 2024\"\n",
    "\n",
    "        if department:\n",
    "            period_label += f\" - {department}\"\n",
    "        if admin_area:\n",
    "            period_label += f\" - {admin_area}\"\n",
    "        if stream:\n",
    "            period_label += f\" - Stream {stream}\"\n",
    "\n",
    "        summary[\"period_label\"] = period_label\n",
    "\n",
    "        # Create AI prompt\n",
    "        prompt = f\"\"\"You are a senior operations analyst for an integrated oil and gas company (upstream, midstream, downstream).\n",
    "\n",
    "Generate a comprehensive operational report based on the following data.\n",
    "\n",
    "CRITICAL INSTRUCTIONS:\n",
    "1. Return ONLY valid JSON (no markdown, no code blocks, no backticks).\n",
    "2. All values must be strings (use \"\\\\n\" for line breaks in text).\n",
    "3. Do not use arrays or nested objects.\n",
    "4. Be specific, analytical, and data-driven.\n",
    "5. Base everything strictly on the provided metrics.\n",
    "\n",
    "CRITICAL - PERCENTAGE INTERPRETATION RULES:\n",
    "- Achievement rate of 102.40% means: Actual = 102.40% OF Target, so actual exceeded target by only 2.40%\n",
    "- Achievement rate of 98.50% means: Actual = 98.50% OF Target, so actual is 1.50% BELOW target\n",
    "- Utilization rate of 101.13% means: we achieved 1.13% MORE than target\n",
    "- CORRECT phrasing: \"exceeded target by 2.40%\" or \"1.13% above target\" or \"achieved 102% of target\"\n",
    "- WRONG phrasing: \"increased by 102%\" or \"utilization stood at 101.13%\" (this is misleading)\n",
    "- Always calculate: (Achievement% - 100%) = actual variance from target\n",
    "- Example: 103.08% achievement = 3.08% above target, NOT 103% increase\n",
    "\n",
    "JSON Structure Required:\n",
    "{{\n",
    "    \"executive_summary\": \"string with detailed summary\",\n",
    "    \"key_insights\": \"string with bullet points using \\\\n- format\",\n",
    "    \"anomalies\": \"string describing issues and concerns\",\n",
    "    \"recommendations\": \"string with actionable recommendations\"\n",
    "}}\n",
    "\n",
    "Reporting Period: {period_label}\n",
    "\n",
    "Metrics Summary:\n",
    "{json.dumps(summary, indent=2)}\n",
    "\n",
    "Analysis Requirements:\n",
    "- Compare actual vs target performance across upstream, midstream, and downstream metrics where available.\n",
    "- Identify efficiency trends and potential bottlenecks by admin area, department, and stream.\n",
    "- Highlight underperforming operational areas and streams.\n",
    "- Assess energy usage and downtime patterns.\n",
    "- Provide root cause analysis where possible based on the metrics.\n",
    "- Give specific, actionable operational recommendations.\n",
    "\n",
    "Generate the report now in pure JSON format:\n",
    "\"\"\"\n",
    "\n",
    "        print(\"Calling Ollama AI...\")\n",
    "\n",
    "        # Call Ollama\n",
    "        response = ollama.chat(\n",
    "            model=\"llama3.1\",\n",
    "            messages=[\n",
    "                {\n",
    "                    \"role\": \"system\",\n",
    "                    \"content\": \"You are an expert petroleum engineer and data analyst. Return only valid JSON with no markdown formatting.\"\n",
    "                },\n",
    "                {\n",
    "                    \"role\": \"user\",\n",
    "                    \"content\": prompt\n",
    "                }\n",
    "            ]\n",
    "        )\n",
    "\n",
    "        raw_response = response[\"message\"][\"content\"]\n",
    "        print(\"Raw Ollama Response (truncated):\")\n",
    "        print(raw_response[:500])\n",
    "\n",
    "        # Clean response\n",
    "        raw_response = raw_response.strip()\n",
    "        raw_response = raw_response.replace(\"```json\", \"\").replace(\"```\", \"\")\n",
    "\n",
    "        # Parse JSON - with enhanced cleaning for newlines in strings\n",
    "        try:\n",
    "            # Fix newlines inside JSON string values\n",
    "            import re\n",
    "            \n",
    "            def fix_json_newlines(json_str):\n",
    "                # This regex finds content between quotes and replaces actual newlines with \\n\n",
    "                result = []\n",
    "                in_string = False\n",
    "                escape_next = False\n",
    "                \n",
    "                for i, char in enumerate(json_str):\n",
    "                    if escape_next:\n",
    "                        result.append(char)\n",
    "                        escape_next = False\n",
    "                        continue\n",
    "                        \n",
    "                    if char == '\\\\':\n",
    "                        escape_next = True\n",
    "                        result.append(char)\n",
    "                        continue\n",
    "                        \n",
    "                    if char == '\"' and not escape_next:\n",
    "                        in_string = not in_string\n",
    "                        result.append(char)\n",
    "                        continue\n",
    "                    \n",
    "                    if in_string and char == '\\n':\n",
    "                        result.append('\\\\n')\n",
    "                    elif in_string and char == '\\r':\n",
    "                        result.append('\\\\r')\n",
    "                    elif in_string and char == '\\t':\n",
    "                        result.append('\\\\t')\n",
    "                    else:\n",
    "                        result.append(char)\n",
    "                \n",
    "                return ''.join(result)\n",
    "            \n",
    "            cleaned_response = fix_json_newlines(raw_response)\n",
    "            report_data = json.loads(cleaned_response)\n",
    "        except json.JSONDecodeError as e:\n",
    "            print(f\"JSON Parse Error: {e}\")\n",
    "            print(f\"Raw response: {raw_response}\")\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"AI generated invalid JSON format\",\n",
    "                \"raw_response\": raw_response\n",
    "            }), 500\n",
    "\n",
    "        # Validate structure\n",
    "        required_fields = [\"executive_summary\", \"key_insights\", \"anomalies\", \"recommendations\"]\n",
    "        for field in required_fields:\n",
    "            if field not in report_data:\n",
    "                return jsonify({\n",
    "                    \"status\": \"error\",\n",
    "                    \"message\": f\"Missing required field: {field}\"\n",
    "                }), 500\n",
    "\n",
    "        # Save to database\n",
    "        now = datetime.now().isoformat()\n",
    "\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        metadata = {\n",
    "            \"filters\": filters,\n",
    "            \"summary\": summary,\n",
    "            \"generated_at\": now\n",
    "        }\n",
    "\n",
    "        cur.execute(\"\"\"\n",
    "            INSERT INTO reports (created_at, updated_at, quarter, report_json, raw_text, metadata)\n",
    "            VALUES (?, ?, ?, ?, ?, ?)\n",
    "        \"\"\", (\n",
    "            now,\n",
    "            now,\n",
    "            quarter or \"all\",\n",
    "            json.dumps(report_data),\n",
    "            raw_response,\n",
    "            json.dumps(metadata)\n",
    "        ))\n",
    "\n",
    "        report_id = cur.lastrowid\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "\n",
    "        print(f\"Report saved with ID: {report_id}\")\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"report_id\": report_id,\n",
    "            \"report\": report_data,\n",
    "            \"metadata\": {\n",
    "                \"period\": period_label,\n",
    "                \"records_analyzed\": len(df_filtered),\n",
    "                \"generated_at\": now\n",
    "            }\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error generating report: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/save-report\", methods=[\"POST\"])\n",
    "def save_report_to_db():\n",
    "    \"\"\"Save complete report with text content, stats, and context to database\"\"\"\n",
    "    try:\n",
    "        payload = request.get_json() or {}\n",
    "        \n",
    "        text_content = payload.get(\"textContent\", {})\n",
    "        stats = payload.get(\"stats\", {})\n",
    "        context = payload.get(\"context\", {})\n",
    "        quarter = payload.get(\"quarter\")\n",
    "        department = payload.get(\"department\")\n",
    "        \n",
    "        if not text_content or len(text_content) == 0:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"No report text content provided\"\n",
    "            }), 400\n",
    "        \n",
    "        now = datetime.now().isoformat()\n",
    "        \n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "        \n",
    "        metadata = {\n",
    "            \"department\": department,\n",
    "            \"saved_at\": now\n",
    "        }\n",
    "        \n",
    "        # Save all components separately for easy retrieval\n",
    "        cur.execute(\"\"\"\n",
    "            INSERT INTO reports (created_at, updated_at, quarter, text_content, stats_json, context_json, metadata, report_json)\n",
    "            VALUES (?, ?, ?, ?, ?, ?, ?, ?)\n",
    "        \"\"\", (\n",
    "            now,\n",
    "            now,\n",
    "            quarter or \"all\",\n",
    "            json.dumps(text_content),\n",
    "            json.dumps(stats),\n",
    "            json.dumps(context),\n",
    "            json.dumps(metadata),\n",
    "            json.dumps({\n",
    "                \"textContent\": text_content,\n",
    "                \"stats\": stats,\n",
    "                \"context\": context\n",
    "            })\n",
    "        ))\n",
    "        \n",
    "        report_id = cur.lastrowid\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "        \n",
    "        print(f\"Report saved to database with ID: {report_id}\")\n",
    "        \n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"report_id\": report_id,\n",
    "            \"message\": \"Report saved successfully to database\"\n",
    "        })\n",
    "    \n",
    "    except Exception as e:\n",
    "        print(f\"Error saving report: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/rewrite\", methods=[\"POST\", \"OPTIONS\"])\n",
    "def rewrite_text():\n",
    "    \"\"\"AI-powered text rewriting using Ollama\"\"\"\n",
    "    \n",
    "    # Handle preflight\n",
    "    if request.method == 'OPTIONS':\n",
    "        return '', 204\n",
    "    \n",
    "    try:\n",
    "        payload = request.get_json() or {}\n",
    "        original_text = payload.get(\"text\", \"\").strip()\n",
    "        instructions = payload.get(\"instructions\", \"Rewrite clearly and professionally.\").strip()\n",
    "\n",
    "        if not original_text:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"No text provided for rewriting\"\n",
    "            }), 400\n",
    "\n",
    "        print(f\"\\n=== Text Rewrite Request ===\")\n",
    "        print(f\"Original length: {len(original_text)} chars\")\n",
    "        print(f\"Instructions: {instructions[:100]}...\")\n",
    "\n",
    "        # Create prompt for Ollama\n",
    "        prompt = f\"\"\"You are a professional business report editor. Your task is to rewrite the following text according to the user's specific instructions.\n",
    "\n",
    "CRITICAL RULES:\n",
    "1. Keep the core meaning and all factual information\n",
    "2. Maintain technical and domain terminology\n",
    "3. Return ONLY the rewritten text (no explanations, no \"Here's the rewritten text:\", no markdown)\n",
    "4. Do not add new information not in the original\n",
    "5. Preserve all numbers and metrics\n",
    "\n",
    "User Instructions: {instructions}\n",
    "\n",
    "Original Text:\n",
    "{original_text}\n",
    "\n",
    "Rewritten Text:\"\"\"\n",
    "\n",
    "        # Call Ollama\n",
    "        response = ollama.chat(\n",
    "            model=\"llama3.1\",\n",
    "            messages=[\n",
    "                {\n",
    "                    \"role\": \"system\",\n",
    "                    \"content\": \"You are an expert business writer. Rewrite text according to user instructions. Return ONLY the rewritten text without any explanation or preamble.\"\n",
    "                },\n",
    "                {\n",
    "                    \"role\": \"user\",\n",
    "                    \"content\": prompt\n",
    "                }\n",
    "            ],\n",
    "            stream=False\n",
    "        )\n",
    "\n",
    "        rewritten_text = response[\"message\"][\"content\"].strip()\n",
    "\n",
    "        # Clean up common Ollama artifacts\n",
    "        rewritten_text = rewritten_text.replace(\"```\", \"\").strip()\n",
    "        if rewritten_text.startswith(\"Rewritten Text:\"):\n",
    "            rewritten_text = rewritten_text.replace(\"Rewritten Text:\", \"\").strip()\n",
    "\n",
    "        print(f\"Rewritten length: {len(rewritten_text)} chars\")\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"rewritten\": rewritten_text,\n",
    "            \"original_length\": len(original_text),\n",
    "            \"rewritten_length\": len(rewritten_text)\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error in /api/rewrite: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/reports\", methods=[\"GET\"])\n",
    "def list_reports():\n",
    "    \"\"\"List all saved reports\"\"\"\n",
    "    try:\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        cur.execute(\"\"\"\n",
    "            SELECT id, created_at, updated_at, quarter, metadata, text_content, context_json\n",
    "            FROM reports\n",
    "            ORDER BY id DESC\n",
    "        \"\"\")\n",
    "\n",
    "        rows = cur.fetchall()\n",
    "        conn.close()\n",
    "\n",
    "        reports = []\n",
    "        for row in rows:\n",
    "            metadata = json.loads(row[4]) if row[4] else {}\n",
    "            text_content = json.loads(row[5]) if row[5] else {}\n",
    "            context = json.loads(row[6]) if row[6] else {}\n",
    "            \n",
    "            # Extract first line of executive summary for preview\n",
    "            preview = text_content.get(\"executive_summary\", \"\")[:150] if text_content else \"\"\n",
    "            \n",
    "            # Get report name from context\n",
    "            report_name = context.get(\"reportName\", \"\") or metadata.get(\"reportName\", \"\")\n",
    "            \n",
    "            reports.append({\n",
    "                \"id\": row[0],\n",
    "                \"created_at\": row[1],\n",
    "                \"updated_at\": row[2],\n",
    "                \"quarter\": row[3],\n",
    "                \"metadata\": metadata,\n",
    "                \"preview\": preview,\n",
    "                \"name\": report_name,\n",
    "                \"context\": context\n",
    "            })\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"reports\": reports,\n",
    "            \"count\": len(reports)\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error listing reports: {e}\")\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/reports/<int:report_id>\", methods=[\"GET\"])\n",
    "def get_report(report_id):\n",
    "    \"\"\"Get a specific report with all details\"\"\"\n",
    "    try:\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        cur.execute(\"\"\"\n",
    "            SELECT id, created_at, updated_at, quarter, report_json, raw_text, metadata, text_content, stats_json, context_json\n",
    "            FROM reports\n",
    "            WHERE id = ?\n",
    "        \"\"\", (report_id,))\n",
    "\n",
    "        row = cur.fetchone()\n",
    "        conn.close()\n",
    "\n",
    "        if not row:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"Report not found\"\n",
    "            }), 404\n",
    "\n",
    "        # Try to get data from new format first\n",
    "        text_content = json.loads(row[7]) if row[7] else None\n",
    "        stats = json.loads(row[8]) if row[8] else None\n",
    "        context = json.loads(row[9]) if row[9] else None\n",
    "        report_data = json.loads(row[4]) if row[4] else {}\n",
    "        metadata = json.loads(row[6]) if row[6] else {}\n",
    "        \n",
    "        # Fallback to old format if new format not available\n",
    "        if not text_content and report_data:\n",
    "            text_content = report_data.get(\"textContent\") or report_data\n",
    "        \n",
    "        if not stats and report_data:\n",
    "            stats = report_data.get(\"stats\", {})\n",
    "        \n",
    "        if not context and report_data:\n",
    "            context = report_data.get(\"context\", {})\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"report\": {\n",
    "                \"id\": row[0],\n",
    "                \"created_at\": row[1],\n",
    "                \"updated_at\": row[2],\n",
    "                \"quarter\": row[3],\n",
    "                \"textContent\": text_content or {},\n",
    "                \"stats\": stats or {},\n",
    "                \"context\": context or {},\n",
    "                \"metadata\": metadata\n",
    "            }\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error getting report: {e}\")\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route('/api/data-range', methods=['POST'])\n",
    "def get_data_range():\n",
    "    \"\"\"Get data by date range\"\"\"\n",
    "    try:\n",
    "        data = request.json or {}\n",
    "        start_date = data.get('startDate')\n",
    "        end_date = data.get('endDate')\n",
    "\n",
    "        if not start_date or not end_date:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"startDate and endDate are required\"\n",
    "            }), 400\n",
    "\n",
    "        df = load_data()\n",
    "\n",
    "        if df.empty:\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"No data available\",\n",
    "                \"data\": [],\n",
    "                \"count\": 0\n",
    "            }), 404\n",
    "\n",
    "        # Filter by date range\n",
    "        df_filtered = df[(df[\"Date\"] >= start_date) & (df[\"Date\"] <= end_date)]\n",
    "\n",
    "        # Convert date to string for JSON\n",
    "        df_filtered[\"Date\"] = df_filtered[\"Date\"].dt.strftime(\"%Y-%m-%d\")\n",
    "\n",
    "        # Clean NaN values\n",
    "        records = df_filtered.to_dict(orient=\"records\")\n",
    "        records = [clean_json_record(r) for r in records]\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"data\": records,\n",
    "            \"count\": len(records)\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error in /api/data-range: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e),\n",
    "            \"data\": [],\n",
    "            \"count\": 0\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/reports/<int:report_id>\", methods=[\"DELETE\"])\n",
    "def delete_report(report_id):\n",
    "    \"\"\"Delete a report\"\"\"\n",
    "    try:\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        cur.execute(\"DELETE FROM reports WHERE id = ?\", (report_id,))\n",
    "\n",
    "        if cur.rowcount == 0:\n",
    "            conn.close()\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"Report not found\"\n",
    "            }), 404\n",
    "\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"message\": \"Report deleted successfully\"\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error deleting report: {e}\")\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/reports/<int:report_id>\", methods=[\"PUT\"])\n",
    "def update_report(report_id):\n",
    "    \"\"\"Update a report\"\"\"\n",
    "    try:\n",
    "        payload = request.get_json() or {}\n",
    "        raw_text = payload.get(\"raw_text\")\n",
    "        text_content = payload.get(\"text_content\")\n",
    "        stats = payload.get(\"stats\")\n",
    "        context = payload.get(\"context\")\n",
    "\n",
    "        now = datetime.now().isoformat()\n",
    "\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        cur.execute(\"\"\"\n",
    "            UPDATE reports\n",
    "            SET raw_text = ?, text_content = ?, stats_json = ?, context_json = ?, updated_at = ?\n",
    "            WHERE id = ?\n",
    "        \"\"\", (\n",
    "            raw_text,\n",
    "            json.dumps(text_content) if text_content else None,\n",
    "            json.dumps(stats) if stats else None,\n",
    "            json.dumps(context) if context else None,\n",
    "            now,\n",
    "            report_id\n",
    "        ))\n",
    "\n",
    "        if cur.rowcount == 0:\n",
    "            conn.close()\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"Report not found\"\n",
    "            }), 404\n",
    "\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"message\": \"Report updated successfully\"\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error updating report: {e}\")\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"message\": str(e)\n",
    "        }), 500\n",
    "\n",
    "\n",
    "# ================================\n",
    "# UPDATE / DELETE / ADD METRICS\n",
    "# ================================\n",
    "\n",
    "@app.route(\"/api/metrics/<int:record_id>\", methods=[\"PUT\"])\n",
    "def update_metric(record_id):\n",
    "    \"\"\"Update single metric record\"\"\"\n",
    "    try:\n",
    "        payload = request.get_json() or {}\n",
    "\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        # Build dynamic SET clause\n",
    "        set_clause = \", \".join([f\"{k} = ?\" for k in payload.keys()])\n",
    "        values = list(payload.values())\n",
    "        values.append(record_id)\n",
    "\n",
    "        cur.execute(f\"UPDATE upstream_metrics SET {set_clause} WHERE id = ?\", values)\n",
    "\n",
    "        if cur.rowcount == 0:\n",
    "            conn.close()\n",
    "            return jsonify({\"status\": \"error\", \"message\": \"Record not found\"}), 404\n",
    "\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "\n",
    "        return jsonify({\"status\": \"ok\", \"message\": \"Record updated successfully\"})\n",
    "\n",
    "    except Exception as e:\n",
    "        return jsonify({\"status\": \"error\", \"message\": str(e)}), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/metrics/<int:record_id>\", methods=[\"DELETE\"])\n",
    "def delete_metric(record_id):\n",
    "    \"\"\"Delete a metric record\"\"\"\n",
    "    try:\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        cur.execute(\"DELETE FROM upstream_metrics WHERE id = ?\", (record_id,))\n",
    "\n",
    "        if cur.rowcount == 0:\n",
    "            conn.close()\n",
    "            return jsonify({\"status\": \"error\", \"message\": \"Record not found\"}), 404\n",
    "\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "\n",
    "        return jsonify({\"status\": \"ok\", \"message\": \"Record deleted successfully\"})\n",
    "\n",
    "    except Exception as e:\n",
    "        return jsonify({\"status\": \"error\", \"message\": str(e)}), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/metrics\", methods=[\"POST\"])\n",
    "def add_metric():\n",
    "    \"\"\"Insert new metric record\"\"\"\n",
    "    try:\n",
    "        payload = request.get_json() or {}\n",
    "\n",
    "        columns = \", \".join(payload.keys())\n",
    "        placeholders = \", \".join([\"?\" for _ in payload.keys()])\n",
    "        values = list(payload.values())\n",
    "\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        cur.execute(\n",
    "            f\"INSERT INTO upstream_metrics ({columns}) VALUES ({placeholders})\",\n",
    "            values\n",
    "        )\n",
    "\n",
    "        new_id = cur.lastrowid\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "\n",
    "        return jsonify({\"status\": \"ok\", \"id\": new_id, \"message\": \"Record added successfully\"})\n",
    "\n",
    "    except Exception as e:\n",
    "        return jsonify({\"status\": \"error\", \"message\": str(e)}), 500\n",
    "\n",
    "\n",
    "# ================================\n",
    "# DEBUG ENDPOINTS\n",
    "# ================================\n",
    "\n",
    "@app.route(\"/api/debug\", methods=[\"GET\"])\n",
    "def debug_info():\n",
    "    \"\"\"Debug endpoint to check database status\"\"\"\n",
    "    try:\n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "\n",
    "        # Check tables\n",
    "        cur.execute(\"SELECT name FROM sqlite_master WHERE type='table'\")\n",
    "        tables = cur.fetchall()\n",
    "\n",
    "        # Check upstream_metrics columns and count\n",
    "        columns = []\n",
    "        row_count = 0\n",
    "        sample = None\n",
    "        col_names = []\n",
    "        if ('upstream_metrics',) in tables:\n",
    "            cur.execute(\"PRAGMA table_info(upstream_metrics)\")\n",
    "            columns = cur.fetchall()\n",
    "            cur.execute(\"SELECT COUNT(*) FROM upstream_metrics\")\n",
    "            row_count = cur.fetchone()[0]\n",
    "\n",
    "            # Get sample data\n",
    "            cur.execute(\"SELECT * FROM upstream_metrics LIMIT 1\")\n",
    "            sample_data = cur.fetchone()\n",
    "            if sample_data:\n",
    "                col_names = [description[0] for description in cur.description]\n",
    "                sample = dict(zip(col_names, sample_data))\n",
    "\n",
    "        conn.close()\n",
    "\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"database_exists\": os.path.exists(DB_PATH),\n",
    "            \"database_path\": os.path.abspath(DB_PATH),\n",
    "            \"tables\": tables,\n",
    "            \"upstream_metrics\": {\n",
    "                \"exists\": ('upstream_metrics',) in tables,\n",
    "                \"row_count\": row_count,\n",
    "                \"columns\": [col[1] for col in columns],\n",
    "                \"sample\": sample\n",
    "            }\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"error\": str(e),\n",
    "            \"traceback\": traceback.format_exc()\n",
    "        }), 500\n",
    "\n",
    "\n",
    "@app.route(\"/api/test\", methods=[\"GET\"])\n",
    "def test_endpoint():\n",
    "    \"\"\"Test endpoint to verify data loading\"\"\"\n",
    "    try:\n",
    "        df = load_data()\n",
    "        return jsonify({\n",
    "            \"status\": \"ok\",\n",
    "            \"data_loaded\": not df.empty,\n",
    "            \"record_count\": len(df),\n",
    "            \"columns\": df.columns.tolist() if not df.empty else []\n",
    "        })\n",
    "    except Exception as e:\n",
    "        return jsonify({\n",
    "            \"status\": \"error\",\n",
    "            \"error\": str(e)\n",
    "        }), 500\n",
    "@app.route(\"/api/metrics/update-by-key\", methods=[\"PUT\"])\n",
    "def update_metric_by_key():\n",
    "    \"\"\"Update metric record by composite key (Date + Stream + Department + AdminArea)\"\"\"\n",
    "    try:\n",
    "        payload = request.get_json() or {}\n",
    "        \n",
    "        # Get original identifying fields\n",
    "        original_date = payload.pop('original_Date', None)\n",
    "        original_stream = payload.pop('original_Stream', None)\n",
    "        original_department = payload.pop('original_Department', None)\n",
    "        original_admin_area = payload.pop('original_AdminArea', None)\n",
    "        \n",
    "        if not all([original_date, original_stream, original_department]):\n",
    "            return jsonify({\n",
    "                \"status\": \"error\",\n",
    "                \"message\": \"Missing required fields: original_Date, original_Stream, original_Department\"\n",
    "            }), 400\n",
    "        \n",
    "        conn = sqlite3.connect(DB_PATH)\n",
    "        cur = conn.cursor()\n",
    "        \n",
    "        # Build dynamic SET clause from remaining payload\n",
    "        set_clause = \", \".join([f\"{k} = ?\" for k in payload.keys()])\n",
    "        values = list(payload.values())\n",
    "        \n",
    "        # Add WHERE clause values\n",
    "        values.extend([original_date, original_stream, original_department])\n",
    "        \n",
    "        where_clause = \"Date = ? AND Stream = ? AND Department = ?\"\n",
    "        if original_admin_area:\n",
    "            where_clause += \" AND AdminArea = ?\"\n",
    "            values.append(original_admin_area)\n",
    "        \n",
    "        sql = f\"UPDATE upstream_metrics SET {set_clause} WHERE {where_clause}\"\n",
    "        print(f\"SQL: {sql}\")\n",
    "        print(f\"Values: {values}\")\n",
    "        \n",
    "        cur.execute(sql, values)\n",
    "        \n",
    "        if cur.rowcount == 0:\n",
    "            conn.close()\n",
    "            return jsonify({\n",
    "                \"status\": \"error\", \n",
    "                \"message\": \"Record not found with given key\"\n",
    "            }), 404\n",
    "        \n",
    "        # Get the updated record's ID\n",
    "        cur.execute(\"\"\"\n",
    "            SELECT id FROM upstream_metrics \n",
    "            WHERE Date = ? AND Stream = ? AND Department = ?\n",
    "            LIMIT 1\n",
    "        \"\"\", (payload.get('Date', original_date), \n",
    "              payload.get('Stream', original_stream), \n",
    "              payload.get('Department', original_department)))\n",
    "        \n",
    "        row = cur.fetchone()\n",
    "        record_id = row[0] if row else None\n",
    "        \n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "        \n",
    "        return jsonify({\n",
    "            \"status\": \"ok\", \n",
    "            \"message\": \"Record updated successfully\",\n",
    "            \"id\": record_id,\n",
    "            \"rows_affected\": cur.rowcount\n",
    "        })\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"Error updating by key: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return jsonify({\"status\": \"error\", \"message\": str(e)}), 500\n",
    "\n",
    "# ================================\n",
    "# STARTUP\n",
    "# ================================\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"=\" * 60)\n",
    "    print(\"Starting Operations API\")\n",
    "    print(\"=\" * 60)\n",
    "\n",
    "    # Check if database exists\n",
    "    if not os.path.exists(DB_PATH):\n",
    "        print(f\"WARNING: Database file '{DB_PATH}' not found at: {os.path.abspath('.')}\")\n",
    "        print(\"Creating empty database...\")\n",
    "\n",
    "    # Initialize database\n",
    "    init_db()\n",
    "\n",
    "    # Load initial data\n",
    "    df_init = load_data()\n",
    "    print(f\"Total records available: {len(df_init)}\")\n",
    "\n",
    "    if not df_init.empty:\n",
    "        print(f\"Date range: {df_init['Date'].min()} to {df_init['Date'].max()}\")\n",
    "        if \"Department\" in df_init.columns:\n",
    "            print(f\"Departments: {df_init['Department'].nunique()}\")\n",
    "        if \"AdminArea\" in df_init.columns:\n",
    "            print(f\"Admin Areas: {df_init['AdminArea'].nunique()}\")\n",
    "\n",
    "    print(\"=\" * 60)\n",
    "    print(\"API Server Ready\")\n",
    "    print(\"Listening on: http://0.0.0.0:8001\")\n",
    "    print(\"Test endpoints:\")\n",
    "    print(\"  - GET /api/health\")\n",
    "    print(\"  - GET /api/debug\")\n",
    "    print(\"  - GET /api/test\")\n",
    "    print(\"  - GET /api/metrics\")\n",
    "    print(\"  - POST /api/rewrite\")\n",
    "    print(\"  - POST /api/save-report (NEW)\")\n",
    "    print(\"=\" * 60)\n",
    "\n",
    "    app.run(host=\"0.0.0.0\", port=8001, debug=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b8d3526-6bff-4771-ad18-11fbc896ffdc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
